### ISSUE TITLE
Binary JRE not working well with printing-module

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#10398]
## Description

When trying to use the printing-module with the binary, WMS layers (I think because of https) can not be printed 
## How to reproduce
- Download the binary and the printing-module (JRE 11, from 2024.01.xx)
- run (to extract mapstore) and stop
- extract printing-module.zip in webapps/mapstore/WEB-INF (classes and lib)
- start again binary
- open the default map
- try to print.

*Expected Result*
- All map is printed.

*Current Result*
- Layers from gs-stable (or gs-main) are not printed (background looks to be working

An exception is present in the log:

```
INFO 2024-06-03 17:33:36.441 org.mapfish.print.output.OutputFactory::create:62 - OutputFormat chosen for jpg is ImageOutputScalable
INFO 2024-06-03 17:33:36.442 org.mapfish.print.output.OutputFactory::create:62 - OutputFormat chosen for jpg is ImageOutputScalable
Exception in thread "Timeout guard" java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1918)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1894)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:82)
	at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1.doit(ControllerThreadSocketFactory.java:91)
	at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$SocketTask.run(ControllerThreadSocketFactory.java:158)
	at java.base/java.lang.Thread.run(Thread.java:829)
INFO 2024-06-03 17:33:36.623 org.mapfish.print.map.readers.WMSServiceInfo::getInfo:53 - Error while getting capabilities for https://gs-stable.geosolutionsgroup.com/geoserver/wms?. The print module will assume it's a standard WMS.
INFO 2024-06-03 17:33:36.623 org.mapfish.print.map.readers.WMSServiceInfo::getInfo:58 - org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:721)
org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
org.mapfish.print.map.readers.ServerInfoCache.requestInfo(ServerInfoCache.java:103)
org.mapfish.print.map.readers.ServerInfoCache.getInfo(ServerInfoCache.java:51)
org.mapfish.print.map.readers.WMSServiceInfo.getInfo(WMSServiceInfo.java:65)
org.mapfish.print.map.readers.WMSMapReader.<init>(WMSMapReader.java:101)
org.mapfish.print.map.readers.WMSMapReader$Factory.create(WMSMapReader.java:84)
org.mapfish.print.map.readers.MapReaderFactoryFinder.create(MapReaderFactoryFinder.java:36)
org.mapfish.print.map.MapChunkDrawer.renderImpl(MapChunkDrawer.java:120)
org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
org.mapfish.print.config.layout.MapBlock$1.render(MapBlock.java:77)
org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:187)
org.mapfish.print.config.layout.MapBlock.render(MapBlock.java:73)
org.mapfish.print.config.layout.Page.render(Page.java:81)
org.mapfish.print.config.layout.Layout.render(Layout.java:64)
org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:31)
org.mapfish.print.output.FileCachingJaiMosaicOutputFactory$ImageOutputScalable.print(FileCachingJaiMosaicOutputFactory.java:84)
org.mapfish.print.MapPrinter.print(MapPrinter.java:177)
org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:386)
org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:186)
org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:114)
javax.servlet.http.HttpServlet.service(HttpServlet.java:515)
javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1698)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.base/java.lang.Thread.run(Thread.java:829)

Exception in thread "Timeout guard" java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1918)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1894)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:82)
	at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1.doit(ControllerThreadSocketFactory.java:91)
	at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$SocketTask.run(ControllerThreadSocketFactory.java:158)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR 2024-06-03 17:33:36.932 org.mapfish.print.PDFCustomBlocks::addError:210 - Error while adding a PDF elementjava.lang.NullPointerException
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
home
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at org.apache.batik.transcoder.print.PrintTranscoder.print(PrintTranscoder.java:308)
	at org.mapfish.print.config.layout.ImageBlock$SvgDrawer.renderImpl(ImageBlock.java:140)
	at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
	at org.mapfish.print.ChunkDrawer.tableLayout(ChunkDrawer.java:49)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:701)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:635)
	at com.lowagie.text.pdf.ColumnText.goComposite(ColumnText.java:1482)
	at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:809)
	at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:797)
	at com.lowagie.text.pdf.PdfPRow.writeCells(PdfPRow.java:506)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:686)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:635)
	at com.lowagie.text.pdf.ColumnText.goComposite(ColumnText.java:1482)
	at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:809)
	at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:797)
	at com.lowagie.text.pdf.PdfPRow.writeCells(PdfPRow.java:506)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:686)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:768)
	at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:720)
	at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:67)
	at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:187)
	at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
	at org.mapfish.print.config.layout.Page.render(Page.java:81)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:64)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:31)
	at org.mapfish.print.output.FileCachingJaiMosaicOutputFactory$ImageOutputScalable.print(FileCachingJaiMosaicOutputFactory.java:84)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:177)
	at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:386)
	at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:186)
	at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:114)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:515)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1698)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.UnknownHostException: home
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
	at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
	at org.apache.batik.util.ParsedURLData.openStreamInternal(ParsedURLData.java:554)
	at org.apache.batik.util.ParsedURLData.openStream(ParsedURLData.java:476)
	at org.apache.batik.util.ParsedURL.openStream(ParsedURL.java:440)
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:159)
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:283)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:129)
	... 59 more
ERROR: null
Enclosed Exception:
null
Enclosed Exception:
home
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

- Using most recent JDK it works, so the problem is caused by the JRE used.

Version tested that works:
```
 jre/linux/bin/java -version
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.23+9-adhoc.root.jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.23+9-adhoc.root.jdk11u, mixed mode)
```

Current version (not working): 
```
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8)
OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)
```

**Comment by offtherailz** [comment]
Closed for out-of-date
