### ISSUE TITLE
Unable to load layer from QGIS Server WMS Demo

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1268]
I can parse the GetCapabilities document [here](http://demo.qgis.org/cgi-bin/qgis_mapserv.fcgi?map=/web/demos/south_perth/project.qgs&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1) but I cannot add any layers.

I see many errors like this one below in the console:

Uncaught TypeError: t.reduce is not a function
    at http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:171:17456
    at n (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:20:29403)
    at e.addLayer (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:171:20615)
    at onClick (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:171:19457)
    at Object.r (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:1:29947)
    at s (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:1:28770)
    at Object.a [as executeDispatchesInOrder] (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:1:28956)
    at p (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:1:25408)
    at f (http://dev.mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js:1:25534)
    at Array.forEach (native)

**Comment by mbarto** [comment]
Fixed by https://github.com/geosolutions-it/MapStore2/pull/1283
That service cannot work because it doesn't provide EPSG:3857, but now the error is clearly shown.
Other QGIS services work (e.g. http://demo.qgis.org/cgi-bin/qgis_mapserv.fcgi/swellendam/?map=/web/demos/swellendam/Swellendam.qgs&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1)

**Comment by simboss** [comment]
This problem is still open.

If you check [this](http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/1689?_k=bkukyb) as an admin you will see that while we are parsing the [GetCapabilities ](http://demo.qgis.org/cgi-bin/qgis_mapserv.fcgi?map=/web/demos/sap/police.qgs&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1) correctly and showing the map, but once we save and reopen, we are losing the portion of the URL that indicates which map we are using (..&map=/web/demos/sap/police.qgs&..) and so WMS requests fails afterwards.

Moreover I noticed that although the WMS version that we have in the GetCapabilities above is 1.1.1 we then make requests using 1.3.0. The version should not be changed between the GetCapabilities and the GetMap!

**Comment by mricca** [comment]
On my side, I solved the issue in this way.
https://github.com/mricca/MapStore2/commit/bc45349433cd68f5cad492f49fe6bab51d6e0587

**Comment by simboss** [comment]
@mricca  a PR would be very much appreciated :)

**Comment by mricca** [comment]
This is my pull requests:
https://github.com/geosolutions-it/MapStore2/pull/1342

**Comment by mbarto** [comment]
Fixed by #1342
