### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oiacrasec** [geosolutions-it/MapStore2#2589]
Hello, i have some questions about the project:

1) Can i connect to another database (like postgres) istead of h2? If yes, how?

2) I see in docs that the MapStore2 main application is inside web/client/product/, is there a way to run main application from npm, like npm start? 

3) Backend application is /web/src/main?

4) When i create the war file and send to tomcat (manager app, upload option). I get this error (is there something with DB i need to configure or create?):

Caused by: org.hibernate.exception.GenericJDBCException: Cannot open connection
        at org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:103)
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:91)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:426)
        at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
        at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
        at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
        at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
        at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:38)
        ... 64 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Error while creating file "/webapps" [90062-168])
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1225)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
        at org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider.getConnection(InjectedDataSourceConnectionProvider.java:47)
        at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
        ... 69 more
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "/webapps" [90062-168]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
        at org.h2.message.DbException.get(DbException.java:169)
        at org.h2.message.DbException.get(DbException.java:146)
        at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:247)
        at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:46)
        at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:300)
        at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:299)
        at org.h2.store.FileLock.lockFile(FileLock.java:327)
        at org.h2.store.FileLock.lock(FileLock.java:129)
        at org.h2.engine.Database.open(Database.java:542)
        at org.h2.engine.Database.openDatabase(Database.java:222)
        at org.h2.engine.Database.<init>(Database.java:217)
        at org.h2.engine.Engine.openSession(Engine.java:56)
        at org.h2.engine.Engine.openSession(Engine.java:159)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:138)
        at org.h2.engine.Engine.createSession(Engine.java:121)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:305)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
        at org.h2.Driver.connect(Driver.java:72)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1247)
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1221)

**Comment by simboss** [comment]
Hi, please use the users mailing list for this kind of feedback.

Check [this](https://mapstore.geo-solutions.it/) page (at the bottom) for a link.
