### ISSUE TITLE
Cannot build in dev env because of babel

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5049]
## Description

Cannot compile when doing npm start

related to https://github.com/facebook/create-react-app/issues/8680

## How to reproduce

- checkout latest master
- npm install
- npm start

*Expected Result*

all working as usual 

*Current Result*

```
ERROR in ./web/client/product/app.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\web\client\product\app.jsx: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\Users\\Matteo\\Documents\\Developer\\geosolutionsProjects\\MapStore2\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at getPlugin (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\preset-env\lib\index.js:67:11)
    at C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\preset-env\lib\index.js:258:62
    at Array.map (<anonymous>)
    at C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\preset-env\lib\index.js:258:43
    at C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\config\full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at step (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\gensync\index.js:254:32)
    at evaluateAsync (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\gensync\index.js:284:5)
    at Function.errback (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\gensync\index.js:108:7)
    at errback (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\gensync\index.js:183:31)
    at onFirstPause (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\gensync\index.js:209:13)
    at Generator.next (<anonymous>)
    at cachedFunction (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\config\caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPresetDescriptor (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\config\full.js:292:44)
    at loadPresetDescriptor.next (<anonymous>)
    at recurseDescriptors (C:\Users\Matteo\Documents\Developer\geosolutionsProjects\MapStore2\node_modules\@babel\core\lib\config\full.js:107:30)
    at recurseDescriptors.next (<anonymous>)

```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Just do the following updates

"@babel/core": "7.8.7",
"@babel/preset-env": "7.8.7",

**Comment by tdipisa** [comment]
@offtherailz please can you provide a backport PR to 2020.01.xx for this? Thank you.
