### ISSUE TITLE
[v2021.02.00] Mapstore fails to start when using LDAP

### ISSUE THREAD

**Issue by shermp** [geosolutions-it/MapStore2#7526]
## Description
When attempting to use LDAP with the release binary/war, Mapstore fails to start.

## How to reproduce
-  Download `mapstore2-2021.02.00-bin.zip`
- Start with `./mapstore2-startup.sh`
- Stop with `./mapstore2-shutdown.sh`
- Replace contents of `webapps/mapstore/WEB-INF/classes/geostore-spring-security.xml` with contents of [geostore-spring-security-ldap.xml](https://github.com/geosolutions-it/MapStore2/blob/v2021.02.00/product/config/ldap/geostore-spring-security-ldap.xml)
- Start with `./mapstore2-startup.sh`

*Expected Result*
Mapstore2 successfully starts.

*Current Result*
Starting Mapstore fails with the following execption (in `logs/mapstore.log`):
```
ERROR   2021-11-10 09:48:59.238   ContextLoader.initWebApplicationContext() - Context initialization failed 
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'contextSource' defined in URL [file:/home/sherman/Documents/mapstore2/webapps/mapstore/WEB-INF/classes/geostore-spring-security.xml]: Could not resolve placeholder 'ldap.userDn'
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:287)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:75)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:663)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:638)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5141)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5664)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

- [x] Not browser related

## Other useful information
`ldap.properties` appears to not be loaded. There is no `Loading properties file...` entry in the log for `ldap.properties`. It doesn't even appear to attempt to load.

**Comment by offtherailz** [comment]
Hi, it seems that it the file not loaded before the application intialization. 
For some reason test environments tested (tomcat7) was working. 
Replacing in `webapps/mapstore/WEB-INF/classes/applicationContext.xml`  `order="10"` with `order="0"` seems to work. Can you give a try? 

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"

	   xmlns:cxf="http://cxf.apache.org/core"
	   xmlns:jaxws="http://cxf.apache.org/jaxws"
       xmlns:jaxrs="http://cxf.apache.org/jaxrs"

       xsi:schemaLocation="
            http://www.springframework.org/schema/beans     http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
            http://cxf.apache.org/jaxws                     http://cxf.apache.org/schemas/jaxws.xsd
            http://cxf.apache.org/jaxrs                     http://cxf.apache.org/schemas/jaxrs.xsd
            http://cxf.apache.org/core                      http://cxf.apache.org/schemas/core.xsd
            http://www.springframework.org/schema/context   http://www.springframework.org/schema/context/spring-context-3.0.xsd"
       default-autowire="byName">

    <context:annotation-config />

    <bean id="geostoreInitializer" class="it.geosolutions.geostore.init.GeoStoreInit" lazy-init="false">
        <!-- Site specific initialization. Please specify a path in the ovr file-->
        <!--<property name="userListInitFile"><null/></property>-->
        <property name="userListInitFile" value="classpath:sample_users.xml"/>
        <!-- Site specific initialization. Please specify a path in the ovr file-->
        <property name="categoryListInitFile" value="classpath:sample_categories.xml" />

        <!-- Site specific initialization. Please specify a path in the ovr file-->
        <property name="userGroupListInitFile" value="classpath:sample_groups.xml" />
        <!-- The default password encoder -->
        <property name="passwordEncoder" ref="${passwordEncoderUsed}"></property>
    </bean>

    <bean class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
        <property name="order" value="0"/>
        <property name="locations">
            <list>
                <value>classpath:geostore.properties</value>
                <value>classpath*:geostore.properties</value>
                <value>classpath:mapstore.properties</value>
                <value>classpath:ldap.properties</value>
                <value>file:${datadir.location:}/mapstore.properties</value>
                <value>file:${datadir.location:}/ldap.properties</value>
            </list>
        </property>
        <property name="ignoreResourceNotFound" value="true"/>
	</bean>
    <!-- Allows getting database configuration also from the data-dir -->
    <bean class="org.springframework.beans.factory.config.PropertyOverrideConfigurer">
        <property name="ignoreResourceNotFound" value="true"/>
        <property name="order" value="10"/>
        <property name="locations">
            <list>
                <value>file:${datadir.location:}/geostore-datasource-ovr.properties</value>
                <value>file:${datadir.location:}/mapstore-ovr.properties</value>
            </list>
        </property>
    </bean>
</beans>
```

**Comment by shermp** [comment]
That seems to have resolved the issue.

I tried just about every other solution I could think of, except what you suggested.
