### ISSUE TITLE
Cesium error 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7586]
Enable the 3D mode on a map a rendering error occurs. 
On console:
> An error occurred while rendering.  Rendering has stopped.
undefined
SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
Error: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at new _ (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:495:19283)
    at V._createTexture (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:538:17677)
    at i.processStateMachine (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:538:5898)
    at r.processStateMachine (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:538:6728)
    at Function.b.processStateMachine (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:538:3566)
    at q.loadTile (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:2107)
    at M (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:20873)
    at O (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:20715)
    at v.endFrame (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:24117)
    at D.endFrame (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:30718)
    at lt (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:6397)
    at ut (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:6472)
    at Te.render (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:14657)
    at P.render (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:557:8739)
    at t (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:556:24253)

**How to Reproduce**
Follow the steps in the gif below:
![3d.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/37ab003b-66ea-421c-a0a9-953d7860d144)

**Comment by offtherailz** [comment]
Thank you @ElenaGallo , I had the same issue and I notified in the issue#7516.
Going to close to not duplicate the discussion.
