### ISSUE TITLE
Build started failing because of terser plugin

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7609]
## Description
Both gitub actions and local build fail because of serveral errors like this 
```
ERROR in pdf.worker.entry.worker.js
pdf.worker.entry.worker.js from Terser plugin
Initiated Worker with invalid execArgv flags: --max_old_space_size=3072
Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --max_old_space_size=3072
    at new Worker (internal/worker.js:161:13)
    at ExperimentalWorker.initialize (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
    at new ExperimentalWorker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
    at WorkerPool.createWorker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
    at new WorkerPool (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new Worker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/index.js:167:26)
    at getWorker (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/index.js:391:9)
    at /home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/index.js:494:41
    at next (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/utils.js:90:7)
    at Array.forEach (<anonymous>)
    at /home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/utils.js:93:26
    at new Promise (<anonymous>)
    at throttleAll (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/utils.js:62:10)
    at TerserPlugin.optimize (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/index.js:651:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ERROR in mapstore2.js
mapstore2.js from Terser plugin
Initiated Worker with invalid execArgv flags: --max_old_space_size=3072
Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --max_old_space_size=3072
    at new Worker (internal/worker.js:161:13)
    at ExperimentalWorker.initialize (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
    at new ExperimentalWorker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
    at WorkerPool.createWorker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
    at new WorkerPool (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new Worker (/home/runner/work/MapStore2/MapStore2/node_modules/jest-worker/build/index.js:167:26)
    at getWorker (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/index.js:391:9)
    at /home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/index.js:494:41
    at next (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/utils.js:90:7)
    at onFulfilled (/home/runner/work/MapStore2/MapStore2/node_modules/terser-webpack-plugin/dist/utils.js:87:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
## How to reproduce
Example : https://github.com/geosolutions-it/MapStore2/runs/4355308254?check_suite_focus=true#step:8:351

Try to build MapStore from today. 
 error. 

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
build passes so going to close

**Comment by MV88** [comment]
can the fact to have ubuntu latest in the workflow be a source of problems?
