### ISSUE TITLE
Error in 3D when terrain is available

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7661]
## Description

An error occours when we try to use a BIL terrain model. QA and STABLE doesn't seems to be affected. 
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/dem3d

https://qa-mapstore.geosolutionsgroup.com/mapstore/#/context/dem3d

## How to reproduce

-  Open this context https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/dem3d (the context is attached)
- Switch to 3D

*Expected Result*
You see the dem (screenshot from qa, same tested on stable)
![image](https://user-images.githubusercontent.com/1279510/146162933-5654f322-7523-443b-8c79-07f1bfbd246c.png)

*Current Result*
Error: 
```
An error occurred while rendering. Rendering has stopped.
TypeError: e.throttleRequestByServer is not a function
TypeError: e.throttleRequestByServer is not a function
    at Object.e.when.e.defined.t.ready.e.defined.t.getHeightmapTerrainDataArray (https://dev-mapstore.geosolutionsgroup.com/mapstore/dist/mapstore2.js?c3654326ac83b2bb94d2:2:1165814)
    at n.e.when.e.defined.t.ready.s.requestTileGeometry (https://dev-mapstore.geosolutionsgroup.com/mapstore/dist/mapstore2.js?c3654326ac83b2bb94d2:2:1166618)
    at m (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:537:25427)
    at g (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:537:25540)
    at m.processLoadStateMachine (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:537:27192)
    at E (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:537:29606)
    at Function.b.processStateMachine (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:538:3135)
    at q.loadTile (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:2107)
    at M (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:20873)
    at O (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:20715)
    at v.endFrame (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:24117)
    at D.endFrame (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:539:30718)
    at lt (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:6397)
    at ut (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:6472)
    at Te.render (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:545:14657)
    at P.render (https://cesium.com/downloads/cesiumjs/releases/1.42/Build/Cesium/Cesium.js:557:8739)
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

[context.zip](https://github.com/geosolutions-it/MapStore2/files/7718131/context.zip)

**Comment by MV88** [comment]
@tdipisa please add here info related to the proxy update

**Comment by tdipisa** [comment]
@MV88 
https://github.com/geosolutions-it/MapStore2/pull/7831#issuecomment-1060879031

**Comment by tdipisa** [comment]
@ElenaGallo I'm going to reopen this because I would like to test it again with the new http-proxy version after #7950 is resolved.
