### ISSUE TITLE
failure to print WMTS background layers coming from non-geoserver services

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#7705]
## Description
this is extracted from georchestra/mapstore2-georchestra#399 as it's not georchestra-project specific and can be easily reproduced on non-georchestra instances such as https://mapstore.geosolutionsgroup.com/mapstore/#/
## How to reproduce
-  add a WMTS service from https://tiles.craig.fr/ortho/service 
- add a layer from that service
- try to print the map

*Expected Result*
we should get a pdf

*Current Result*
java traceback coming from mapfishprint
```
Error on printing: Error while generating PDF:
org.mapfish.print.JsonMissingException: attribute [spec.layers[1].style] missing
    at org.mapfish.print.utils.PJsonObject.getString(PJsonObject.java:56)
    at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:78)
```

the error is slightly different if the WMTS layer is configured as a background layer in the map loaded at startup, reproduced with https://wxs.ign.fr/essentiels/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities which chokes on missing `requestEncoding` parameter because there's not default to KVP.

```
Error while generating PDF:
org.mapfish.print.JsonMissingException: attribute [spec.layers[0].requestEncoding] missing
	at org.mapfish.print.utils.PJsonObject.getString(PJsonObject.java:56)
	at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:75)
```

- [x] Not browser related

## Other useful information
most of my findings/time spent analysing it is in georchestra/mapstore2-georchestra#399

a potential fix (to be improved) is this:
```
--- a/web/client/utils/PrintUtils.js
+++ b/web/client/utils/PrintUtils.js
@@ -460,9 +460,9 @@ export const specCreators = {
                 ...dimensionParams,
                 "matrixIds": matrixIds,
                 "matrixSet": tileMatrixSetName,
-                "style": layer.style,
+                "style": layer.style || 'default',
                 "name": layer.name,
-                "requestEncoding": layer.requestEncoding === "RESTful" ? "REST" : layer.requestEncoding,
+                "requestEncoding": layer.requestEncoding === "RESTful" ? "REST" : layer.requestEncoding || 'KVP',
                 "opacity": getOpacity(layer),
                 "version": layer.version || "1.0.0"
             };
```
it would be much better if the only style found in getcapabilities could be considered the default style instead of only looking for `isDefault` attribute which isnt mandated by the OGC WMTS spec.

**Comment by landryb** [comment]
i've looked at `getDefaultStyleIdentifier` in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/WMTSUtils.js#L102 and what was done in 1358cbbf6 should be imo extended to return the first entry, not checking for `.isDefault` if `layer.Style` array contains a single entry.

that wont prevent printing crashes when there's no style at all (which was "worked around" by 1358cbbf6), so maybe there should still be a failsafe/default value when printing (eg my `"style": layer.style || 'default'` proposal) but that would fix the issue with services that dont set the non-mandatory `isDefault` attribute.

**Comment by landryb** [comment]
6e55b89 tries to do that but i havent tested yet that it works, and the coding style is probably horrible anyway. @offtherailz ?

**Comment by landryb** [comment]
fwiw i dunno if that's a scaling issue or something related to WMTS itself, but whatever the printing scale (eg 'round' scales ala `1:10000` in `config.yaml` or webmercator-cache scales (eg `1:17062`) the pdf contains 'white lines' for tile borders, which are probably due to mfprint sortof reassembling the tiles but 'not exactly right'.

![image](https://user-images.githubusercontent.com/3421760/151829509-e6cf7b78-3809-4a28-a401-48640d6b48fa.png)
