### ISSUE TITLE
missing svg when printing/exporting pdf

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#7807]
## Description
i've tried replacing the `print_header.png`shipped in ms2-georchestra by a nice svg file, failed, and realized that also `Arrow_North_CFCF.svg` wasnt included in the generated pdf file.

Then i looked at upstream mapstore, which is also supposed to embed the north arrow (per https://github.com/geosolutions-it/MapStore2/blob/master/java/printing/resources/geoserver/print/config.yaml#L110) and noticed it wasnt working there either - so it doesnt seem to be a configuration issue but somewhere in mfprint/batik ?

## How to reproduce
- try printing pdf on https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/8129
- no north arrow embedded

first, i noticed that the config for the PNG header didnt use `file:` prefix, which doesn't seem to be an issue for PNGs (as printing a pdf with a PNG header works) but fails with SVGs, resulting in `Unable to make sense of URL for connection` exceptions.

Fine, so i added `file:` to the header path, eg:
```
url: 'file:/${configDir}/bando_mapstore_impression.svg'
```

that didnt help, but the exception was now different:
```
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
etc
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.transcoder.print.PrintTranscoder.print(PrintTranscoder.java:307)
        at org.mapfish.print.config.layout.ImageBlock$SvgDrawer.renderImpl(ImageBlock.java:198)
        at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
        at org.mapfish.print.ChunkDrawer.tableLayout(ChunkDrawer.java:49)
```
- [x] Not browser related

so something in the bundled batik 1.7 (old?) chokes on SVG files, and i havent been able to figure out what. It seems to affect ms2 and ms2-geor.

That exception seems to point at the `IOException` in https://github.com/apache/xmlgraphics-batik/blob/f79ce602fa6244d2a7ff45b57b6a0347e883bc37/batik-transcoder/src/main/java/org/apache/batik/transcoder/XMLAbstractTranscoder.java#L107 - dunno if its a problem with *reading* the source svg (shouldnt be, as its readable by tomcat) or if batik tries to fetch an xml schema to validate the svg or something else..

**Comment by landryb** [comment]
At first i thought this was an issue with the two (conflicting?) xercesImpl jars (eg 2.4.0 and 2.6.2) but the error persists with 2.4.0 moved aside. That's with java8 from adoptopenjdk, if that matters.

**Comment by landryb** [comment]
digging a bit more, the `file:/` prefix seems bogus, it should be `file://`...... so the default config needs fixing.

**Comment by landryb** [comment]
with `file://` prefixes before `${configDir}` i have a working pdf export with svg header & north arrow within ms2-georchestra.
