### ISSUE TITLE
http-proxy not working

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7938]
## How to reproduce

-  Run mapstore (or use dev instance)
- try to proxy a request: e.g. http://localhost:8080/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities
(replace http://localhost:8080/mapstore with your mapstore url. e.g. on dev https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities )

*Expected Result*
The request is proxyed

*Current Result*
Blank page. 

logs:
```
[WARNING] [talledLocalContainer] [http-nio-8080-exec-4] ERROR it.geosolutions.httpproxy.HTTPProxy - Error executing HTTP method
[INFO] [talledLocalContainer] java.lang.IllegalArgumentException: Proxy host may not be null
[INFO] [talledLocalContainer]   at org.apache.http.util.Args.notNull(Args.java:54)
[INFO] [talledLocalContainer]   at org.apache.http.conn.routing.HttpRoute.<init>(HttpRoute.java:197)
[INFO] [talledLocalContainer]   at it.geosolutions.httpproxy.HTTPProxy$1.determineRoute(HTTPProxy.java:216)
[INFO] [talledLocalContainer]   at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
[INFO] [talledLocalContainer]   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[INFO] [talledLocalContainer]   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[INFO] [talledLocalContainer]   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
[INFO] [talledLocalContainer]   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
[INFO] [talledLocalContainer]   at it.geosolutions.httpproxy.HTTPProxy.executeProxyRequest(HTTPProxy.java:693)
[INFO] [talledLocalContainer]   at it.geosolutions.httpproxy.HTTPProxy.doGet(HTTPProxy.java:332)
[INFO] [talledLocalContainer]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
[INFO] [talledLocalContainer]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:232)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
[INFO] [talledLocalContainer]   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
[INFO] [talledLocalContainer]   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
[INFO] [talledLocalContainer]   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
[INFO] [talledLocalContainer]   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
[INFO] [talledLocalContainer]   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
[INFO] [talledLocalContainer]   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624)
[INFO] [talledLocalContainer]   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
[INFO] [talledLocalContainer]   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:748)
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
A blank page is anyway a bad behavior. It should show an error

**Comment by tdipisa** [comment]
We can't be dependent on this issue @offtherailz for the MS release. Please, let's go back to using http-proxy 1.1-SNAPSHOT for MS DEV and v1.1.1 for QA. In the meantime we can schedule a fix in http-proxy for this issue to include it in the next minor version of MS (2022.01.01).
@taba90 I think http-proxy v1.3.0 and 1.3.x could be removed at this stage.

**Comment by offtherailz** [comment]
Ok, I'm going to do it. About the http-proxy tag, I fixed it. it was only github wrong tag position, mvn repo and branches was fine.

**Comment by offtherailz** [comment]
This need to be tested on Master and on QA, as well if it get working 
@ElenaGallo @tdipisa

**Comment by tdipisa** [comment]
@ElenaGallo we necessarily need to keep it open to fix the http-proxy issue. @taba90 or @offtherailz can you please improve the description reporting the result of the investigation? That means what is effectively the problem and which versions of http-proxy are affected

Then @taba90 we have to consider also what I reported [above](https://github.com/geosolutions-it/MapStore2/issues/7938#issuecomment-1062993475):

>@taba90, considering the above, I think http-proxy v1.3.0 tag and 1.3.x branch could be removed at this stage and http-proxy can switch back to 1.3-SNAPSHOT.

**Comment by tdipisa** [comment]
@offtherailz I saw you have already opened #7950 to keep track of the work. Ok, thank you. Let's keep then the new one in favor of this.
