### ISSUE TITLE
Local backend not running in a standard created project (2022.01.xx)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8153]
## Description

Backend in cargo is not starting correctly
```
Caused by: java.lang.IllegalArgumentException: More than one fragment with the name [spring_web] 
was found. This is not legal with relative ordering. See section 8.2.2 2c of the Servlet specification for details. 
Consider using absolute ordering
```

## How to reproduce

- `git clone --recursive https://github.com/geosolutions-it/geotour`
- `cd geotour`
- `npm install`
- open a shell and run `npm run backend`
- in another shell run `npm start`

*Expected Result*

opening localhost:8081/# you should be able to see no errors and an empty home page

*Current Result*

it does not work
![image](https://user-images.githubusercontent.com/11991428/165985753-2b00c9b3-5a8e-4865-844d-7d7704228dad.png)

```
 npm run backend

> geotour@1.0.0 backend C:\Work\projects\AAA_Geosolutions\GeoTour
> npm run build-backend && mvn cargo:run -f ./web/pom.xml

[INFO] [talledLocalContainer] apr 29, 2022 6:20:01 PM org.apache.catalina.startup.Catalina stopServer
[INFO] [talledLocalContainer] SEVERE
> geotour@1.0.0 build-backend C:\Work\projects\AAA_Geosolutions\GeoTour
> mvn clean install

: Could not contact [localhost:8205]. Tomcat may not be running.
[INFO] [talledLocalContainer] apr 29, 2022 6:20:01 PM org.apache.catalina.startup.Catalina stopServer
[INFO] [talledLocalContainer] SEVERE: Catalina.stop: 
[INFO] [talledLocalContainer] java.net.ConnectException: Connection refused: connect
[INFO] [talledLocalContainer]   at java.base/java.net.PlainSocketImpl.connect0(Native Method)
[INFO] [talledLocalContainer]   at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
[INFO] [talledLocalContainer]   at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[INFO] [talledLocalContainer]   at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[INFO] [talledLocalContainer]   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[INFO] [talledLocalContainer]   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[INFO] [talledLocalContainer]   at java.base/java.net.Socket.connect(Socket.java:608)
[INFO] [talledLocalContainer]   at java.base/java.net.Socket.connect(Socket.java:557)
[INFO] [talledLocalContainer]   at java.base/java.net.Socket.<init>(Socket.java:453)
[INFO] [talledLocalContainer]   at java.base/java.net.Socket.<init>(Socket.java:230)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:504)
[INFO] [talledLocalContainer]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] [talledLocalContainer]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] [talledLocalContainer]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] [talledLocalContainer]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:391)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:481)
[INFO] [talledLocalContainer] 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for it.geosolutions.GeoTour:GeoTour-web:war:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.cargo:cargo-maven3-plugin is missing. @ line 387, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] GeoTour - Root Project                                             [pom]
[INFO] project for creating a geotour plugin for the dev training - WAR   [war]
[INFO] MapStore 2 - Backend Services                                      [jar]
[INFO] 
[INFO] ----------------< it.geosolutions.GeoTour:GeoTour-root >----------------
[INFO] Building GeoTour - Root Project 1.0-SNAPSHOT                       [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ GeoTour-root ---
[INFO] [talledLocalContainer] Tomcat 8.x is stopped
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ GeoTour-root ---
[INFO] Installing C:\Work\projects\AAA_Geosolutions\GeoTour\pom.xml to C:\Users\user\.m2\repository\it\geosolutions\GeoTour\GeoTour-root\1.0-SNAPSHOT\GeoTour-root-1.0-SNAPSHOT.pom
[INFO] 
[INFO] ----------------< it.geosolutions.GeoTour:GeoTour-web >-----------------
[INFO] Building project for creating a geotour plugin for the dev training - WAR 1.0-SNAPSHOT [2/3]
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ GeoTour-web ---
[INFO] Deleting C:\Work\projects\AAA_Geosolutions\GeoTour\web\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ GeoTour-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (version) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (only index.html) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (only embedded.html) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (only dashboard-embedded.html) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (only geostory-embedded.html) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (only api.html) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (html, configuration files and images) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 19 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (js files) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\..\dist
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (CSS files) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (translations) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (printing) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-resources-plugin:2.6:copy-resources (translations-ms2) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (config files) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ GeoTour-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Work\projects\AAA_Geosolutions\GeoTour\web\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ GeoTour-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ GeoTour-web ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-war-plugin:2.1.1:war (default-war) @ GeoTour-web ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/user/.m2/repository/com/thoughtworks/xstream/xstream/1.3.1/xstream-1.3.1.jar) to field java.util.Properties.defaults
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Packaging webapp
[INFO] Assembling webapp [GeoTour-web] in [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\GeoTour]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Work\projects\AAA_Geosolutions\GeoTour\web\src\main\webapp]
[INFO] Processing overlay [ id it.geosolutions.geostore:geostore-webapp]
[INFO] Processing overlay [ id proxy:http_proxy]
[INFO] Webapp assembled in [4702 msecs]
[INFO] Building war: C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\GeoTour.war
[WARNING] Warning: selected war files include a WEB-INF/web.xml which will be ignored 
(webxml attribute is missing from war task, or ignoreWebxml attribute is specified as 'true')
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ GeoTour-web ---
[INFO] Installing C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\GeoTour.war to C:\Users\user\.m2\repository\it\geosolutions\GeoTour\GeoTour-web\1.0-SNAPSHOT\GeoTour-web-1.0-SNAPSHOT.war
[INFO] Installing C:\Work\projects\AAA_Geosolutions\GeoTour\web\pom.xml to C:\Users\user\.m2\repository\it\geosolutions\GeoTour\GeoTour-web\1.0-SNAPSHOT\GeoTour-web-1.0-SNAPSHOT.pom
[INFO] 
[INFO] -------------< it.geosolutions.mapstore:mapstore-services >-------------
[INFO] Building MapStore 2 - Backend Services 1.3-SNAPSHOT                [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mapstore-services ---
[INFO] Deleting C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mapstore-services ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ mapstore-services ---
[INFO] Compiling 8 source files to C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mapstore-services ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ mapstore-services ---
[INFO] Compiling 7 source files to C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mapstore-services ---
[INFO] Surefire report directory: C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.geosolutions.mapstore.ConfigControllerTest
log4j:WARN No appenders could be found for logger (eu.medsea.mimeutil.TextMimeDetector).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/C:/Users/user/.m2/repository/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.89 sec
Running it.geosolutions.mapstore.ExtensionsControllerTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec
Running it.geosolutions.mapstore.LoadAssetControllerTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.067 sec
Running it.geosolutions.mapstore.SetParamsControllerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running it.geosolutions.mapstore.UploadPluginControllerTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 sec
Running it.geosolutions.mapstore.utils.ResourceUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 42, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] Installing C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\target\mapstore-services-1.3-SNAPSHOT.jar to C:\Users\user\.m2\repository\it\geosolutions\mapstore\mapstore-services\1.3-SNAPSHOT\mapstore-ser.3-SNAPSHOT.jarvices-1.3-SNAPSHOT.jar
[INFO] Installing C:\Work\projects\AAA_Geosolutions\GeoTour\MapStore2\java\services\pom.xml to C:\Users\user\.m2\repository\it\geosolutions\mapstore\mapstore-services\1.3-SNAPSHOT\mapstore-services-1.3-SNAPSHOT.pom            SNAPSHOT.jar to C:\Users\user\.m2\repository\it
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:                                                                                          repository\it\geosolutions\mapstore\mapstore-se
[INFO]
[INFO] GeoTour - Root Project 1.0-SNAPSHOT ................ SUCCESS [  0.503 s]
[INFO] project for creating a geotour plugin for the dev training - WAR 1.0-SNAPSHOT SUCCESS [ 25.299 s]
[INFO] MapStore 2 - Backend Services 1.3-SNAPSHOT ......... SUCCESS [  6.042 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.278 s
[INFO] Finished at: 2022-04-29T18:20:35+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for it.geosolutions.GeoTour:GeoTour-web:war:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.cargo:cargo-maven3-plugin is missing. @ line 387, column 17                                                                                                             eb:war:1.0-SNAPSHOT
[WARNING]                                                                                                        n 17
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.      
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.       
[WARNING]
[INFO]
[INFO] ----------------< it.geosolutions.GeoTour:GeoTour-web >-----------------
[INFO] Building project for creating a geotour plugin for the dev training - WAR 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- cargo-maven3-plugin:1.9.7:run (default-cli) @ GeoTour-web ---
[INFO] [en3.ContainerRunMojo] Resolved container artifact org.codehaus.cargo:cargo-core-container-tomcat:jar:1.9.7 for container tomcat8x                                                                                         7 for container tomcat8x
[INFO] [talledLocalContainer] Tomcat 8.x starting...
[INFO] [stalledLocalDeployer] Deploying [C:\Work\projects\AAA_Geosolutions\GeoTour\.\web\target\GeoTour.war] to [C:\Work\projects\AAA_Geosolutions\GeoTour\.\webC:\Work\projects\AAA_Geosolutions\GeoTour\.\web\target/apache-tomcat-8.5.69\webapps]...
[INFO] [talledLocalContainer] apr 29, 2022 6:20:45 PM org.apache.catalina.startup.SetAllPropertiesRule begin
[WARNING] [talledLocalContainer] WARNING: [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'emptySessionPath' to 'cargo.tomcat.connector.emptySessionPath' did not find a matching property.
[INFO] [talledLocalContainer] apr 29, 2022 6:20:45 PM org.apache.coyote.AbstractProtocol init
[INFO] [talledLocalContainer] INFO: Initializing ProtocolHandler ["http-nio-8080"]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:45 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
[INFO] [talledLocalContainer] INFO: Using a shared selector for servlet write/read
[INFO] [talledLocalContainer] apr 29, 2022 6:20:46 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deploying web application archive [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\cargocpc.war]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:46 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
[WARNING] [talledLocalContainer] WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [105] milliseconds.
[INFO] [talledLocalContainer] apr 29, 2022 6:20:46 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deployment of web application archive [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\cargocpc.war] has finished in [469] ms
[INFO] [talledLocalContainer] apr 29, 2022 6:20:46 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deploying web application archive [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\mapstore.war]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.core.ContainerBase addChildInternal
[INFO] [talledLocalContainer] SEVERE: ContainerBase.addChild: start:
[INFO] [talledLocalContainer] org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/mapstore]]
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)       
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)        
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[INFO] [talledLocalContainer]   at java.base/java.lang.Thread.run(Thread.java:834)
[INFO] [talledLocalContainer] Caused by: java.lang.IllegalArgumentException: More than one fragment with the name [spring_web] was found. This is not legal with relative ordering. See section 8.2.2 2c of the Servlet specification for details. Consider using absolute ordering.
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2206)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2164)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1084)  
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5130)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
[INFO] [talledLocalContainer]   ... 10 more
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] SEVERE: Error deploying web application archive [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\mapstore.war]
[INFO] [talledLocalContainer] java.lang.IllegalStateException: Error starting child
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)       
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)        
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[INFO] [talledLocalContainer]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[INFO] [talledLocalContainer]   at java.base/java.lang.Thread.run(Thread.java:834)
[INFO] [talledLocalContainer] Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/mapstore]]
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
[INFO] [talledLocalContainer]   ... 9 more
[INFO] [talledLocalContainer] Caused by: java.lang.IllegalArgumentException: More than one fragment with the name [spring_web] was found. This is not legal with relative ordering. See section 8.2.2 2c of the Servlet specification for details. Consider using absolute ordering.
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2206)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.descriptor.web.WebXml.orderWebFragments(WebXml.java:2164)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1084)  
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779)
[INFO] [talledLocalContainer]   at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5130)
[INFO] [talledLocalContainer]   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
[INFO] [talledLocalContainer]   ... 10 more
[INFO] [talledLocalContainer]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployWAR
[INFO] [talledLocalContainer] INFO: Deployment of web application archive [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\mapstore.war] has finished in [5,065] ms
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deploying web application directory [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\host-manager]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployDirectory
[INFO] [talledLocalContainer] INFO: Deployment of web application directory [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\host-manager] has finished in [81] ms
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployDirectory     
[INFO] [talledLocalContainer] INFO: Deploying web application directory [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\manager]
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.catalina.startup.HostConfig deployDirectory     
[INFO] [talledLocalContainer] INFO: Deployment of web application directory [C:\Work\projects\AAA_Geosolutions\GeoTour\web\target\apache-tomcat-8.5.69\webapps\manager] has finished in [44] ms
[INFO] [talledLocalContainer] apr 29, 2022 6:20:51 PM org.apache.coyote.AbstractProtocol start
[INFO] [talledLocalContainer] INFO: Starting ProtocolHandler ["http-nio-8080"]
[INFO] [talledLocalContainer] Tomcat 8.x started on port [8080]
[INFO] Press Ctrl-C to stop the container...
[INFO] [talledLocalContainer] Tomcat 8.x is stopping...
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
This is present not only in cargo, but also if you build it with printing module and deploy it in a tomcat

**Comment by taba90** [comment]
The template for the production of project out of the base MapStore2 points to 1.3.0 https://github.com/geosolutions-it/MapStore2/blob/5490458cfd8538a6195e519dcaa4ea20becb8a8d/project/standard/templates/web/pom.xml#L24
version of mapstore services that brings in older spring dependencies.
If it is ok to have the snapshot dependency inside the template pom of 2022.01.xx then chaging it to 1.3-SNAPSHOT (alingned with dependencies updates) will fix the issue.
Otherwise a release for mapstore-services 1.3.1 is needed.
@tdipisa @offtherailz let me know which option do you prefer

**Comment by tdipisa** [comment]
@taba90 ok with this today for a quick test

>If it is ok to have the snapshot dependency inside the template pom of 2022.01.xx then chaging it to 1.3-SNAPSHOT (alingned with dependencies updates) will fix the issue.

Then tomorrow we will release

**Comment by taba90** [comment]
open pr to 2022.01.xx https://github.com/geosolutions-it/MapStore2/pull/8155
