### ISSUE TITLE
cannot export data using viewport

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9201]
### Environment

- [ ] dev
- [ ] pre-prod
- [ ] prod

### How to reproduce

- open this map https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358 
- select states in toc
- export data
- select crop datasst using viewport

*Expected Result*

to work
*Current Result*

error

![image](https://github.com/geosolutions-it/webmapper-halliburton/assets/11991428/469549ef-7298-4faa-a2aa-62a150ffe0e0)

![image](https://github.com/geosolutions-it/webmapper-halliburton/assets/11991428/1c076ea5-e24d-472f-8621-1dcf19c7b9df)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

also the notification message is not very visible

**Comment by allyoucanmap** [comment]
@tdipisa currently it's not possible to test this, it seems the download wps process is missing on [geoserver](https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=DescribeProcess&IDENTIFIER=gs%3ADownloadEstimator%2Cgs%3ADownload) instance

![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/7ea15ba3-f4cc-4729-9cc9-dd40f2ed431b)

**Comment by tdipisa** [comment]
are you autenticated as an user in geosolutions group @allyoucanmap ? the WPS is protected in our GS

**Comment by MV88** [comment]
in that case should we disable the wps related funcionality in advance?

**Comment by tdipisa** [comment]
> in that case should we disable the wps related funcionality in advance?

@MV88 a preventive check is already done by the application automatically. If you are gest or a user with no rights for this only the download via WFS is provided.

**Comment by tdipisa** [comment]
All seems to work as expected for me in DEV @allyoucanmap. just let me know if you need a more in-dept sync for.

**Comment by allyoucanmap** [comment]
@tdipisa I was able to make it work locally, thanks

**Comment by allyoucanmap** [comment]
@tdipisa The download estimator process is using a GeoJSON to represent the ROI for the request, here an example

POST url `/geoserver/wps?service=WPS&version=1.0.0&REQUEST=Execute`

POST body

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs"
    xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc"
    xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
    <ows:Identifier>gs:DownloadEstimator</ows:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <ows:Identifier>layerName</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>gs:us_states</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>ROI</ows:Identifier>
            <wps:Data>
                <wps:ComplexData mimeType="application/json">
                    <![CDATA[{"type":"Polygon","coordinates":[[[-8967145.107169002,4492967.9794719955],[-8967145.107169002,5643803.877333608],[-7614515.454634524,5643803.877333608],[-7614515.454634524,4492967.9794719955],[-8967145.107169002,4492967.9794719955]]]}]]>
                </wps:ComplexData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>RoiCRS</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>EPSG:3857</wps:LiteralData>
            </wps:Data>
        </wps:Input>
    </wps:DataInputs>
</wps:Execute>
```

The response is failing even if from the [documentation](https://docs.geoserver.org/latest/en/user/extensions/wps-download/rawDownload.html#roi-definition) the ROI could be defined as a GeoJSON

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ows="http://www.opengis.net/ows/1.1"
	xmlns:wps="http://www.opengis.net/wps/1.0.0"
	xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="https://gs-stable.geosolutionsgroup.com/geoserver/ows" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:DownloadEstimator</ows:Identifier>
		<ows:Title>Estimator Process</ows:Title>
		<ows:Abstract>Checks if the input file does not exceed the limits</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2023-06-09T15:36:04.345Z">
		<wps:ProcessFailed>
			<ows:ExceptionReport version="1.1.0">
				<ows:Exception exceptionCode="NoApplicableCode">
					<ows:ExceptionText>Failed to retrieve value for input ROI</ows:ExceptionText>
				</ows:Exception>
			</ows:ExceptionReport>
		</wps:ProcessFailed>
	</wps:Status>
</wps:ExecuteResponse>
```

I did an additional test by converting the ROI to WKT instead of GeoJSON

POST url `/geoserver/wps?service=WPS&version=1.0.0&REQUEST=Execute`

POST body

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs"
    xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc"
    xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
    <ows:Identifier>gs:DownloadEstimator</ows:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <ows:Identifier>layerName</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>gs:us_states</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>ROI</ows:Identifier>
            <wps:Data>
                <wps:ComplexData mimeType="application/wkt">
                    <![CDATA[POLYGON (( -8967145.107169002 4492967.9794719955, -8967145.107169002 5643803.877333608, -7614515.454634524 5643803.877333608, -7614515.454634524 4492967.9794719955, -8967145.107169002 4492967.9794719955 ))]]>
                </wps:ComplexData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>RoiCRS</ows:Identifier>
            <wps:Data>
                <wps:LiteralData>EPSG:3857</wps:LiteralData>
            </wps:Data>
        </wps:Input>
    </wps:DataInputs>
</wps:Execute>
```

Now the result of the estimator seems successful

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ows="http://www.opengis.net/ows/1.1"
	xmlns:wps="http://www.opengis.net/wps/1.0.0"
	xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="https://gs-stable.geosolutionsgroup.com/geoserver/ows" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:DownloadEstimator</ows:Identifier>
		<ows:Title>Estimator Process</ows:Title>
		<ows:Abstract>Checks if the input file does not exceed the limits</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2023-06-09T15:40:36.074Z">
		<wps:ProcessSucceeded>Process succeeded.</wps:ProcessSucceeded>
	</wps:Status>
	<wps:ProcessOutputs>
		<wps:Output>
			<ows:Identifier>result</ows:Identifier>
			<ows:Title>Download Limits are respected or not!</ows:Title>
			<wps:Data>
				<wps:LiteralData>true</wps:LiteralData>
			</wps:Data>
		</wps:Output>
	</wps:ProcessOutputs>
</wps:ExecuteResponse>
```

I temporary converted the ROI request to WKT on my local branch and it seems to work as expected anyway probably we need a double check on this one backend side

**Comment by tdipisa** [comment]
@allyoucanmap thank you so much for the investigation. @aaime I suppose this could be a bug for which a JIRA should be opened on the GS side, right?

**Comment by aaime** [comment]
Yes, it looks like a legit issue. How did it pop up? A GeoServer upgrade?

The actual error found in the logs:

```
org.geoserver.wps.WPSException: Failed to retrieve value for input ROI
	at org.geoserver.wps.executor.LazyInputMap.parseInputs(LazyInputMap.java:98)
	at org.geoserver.wps.executor.LazyInputMap.get(LazyInputMap.java:50)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.buildProcessArguments(AnnotationDrivenProcessFactory.java:748)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:628)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:50)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:222)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:191)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at com.bedatadriven.jackson.datatype.jts.serialization.GeometryDeserializer.deserialize(GeometryDeserializer.java:45)
	at com.bedatadriven.jackson.datatype.jts.serialization.GeometryDeserializer.deserialize(GeometryDeserializer.java:33)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at org.geoserver.wps.ppio.GeoJSONPPIO$Geometries.decode(GeoJSONPPIO.java:134)
	at org.geoserver.wps.ppio.CDataPPIO.decode(CDataPPIO.java:21)
	at org.geoserver.wps.executor.SimpleInputProvider.getValueInternal(SimpleInputProvider.java:81)
	at org.geoserver.wps.executor.AbstractInputProvider.getValue(AbstractInputProvider.java:103)
	at org.geoserver.wps.executor.LazyInputMap.parseInputs(LazyInputMap.java:90)
	... 10 more
```

**Comment by tdipisa** [comment]
@aaime

>How did it pop up?

As reported [above](https://github.com/geosolutions-it/MapStore2/issues/9201#issuecomment-1584799285) by making a WPS download request from MS to fix this issue. 

>A GeoServer upgrade?
 
I don't know the last time our gs-stable (that is running version 2.21-SNAPSHOT) has been updated.

**Comment by tdipisa** [comment]
Notified the GS issue to @nmco to open a JIRA. Closing the issue for now.

**Comment by offtherailz** [comment]
JFI: Same issue found trying to download rasters from gs_stable.

**Comment by offtherailz** [comment]
I did an nvestigation for a work of proting features and it follows the following flowchart

```mermaid
flowchart TD
    A[Start] --> B{Has attributes.}
    B -->|Yes| C[execute DownloadEsimator]
    C --> D[execute gs:Download]
    D --> E[execute vec:Query]
    B -->|No| F[DownloadEstimator]
    F --> G[Download]
```
**Has attributes** means "If feature grid has hidden some column. In this case it uses at the end the process of vec:Query because attributes can not be excluded from the normal download, **but** it doesn't support crop. 

CropData anyway actually always fails because it doesn't recognize the crop area.

Many raster fail because they don't pass the limits (crop data do not work, so we can not crop and reduce size). ArcGrid instead passes, because is a very small file (Black marble fails instead).
